// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PicShare_GCPDemo.Models;
using System;

namespace PicShare_GCPDemo.Migrations
{
    [DbContext(typeof(PicShareContext))]
    partial class PicShareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PicShare_GCPDemo.Models.Picture", b =>
                {
                    b.Property<int>("PictureId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("AddedDate");

                    b.Property<string>("Caption");

                    b.Property<string>("FilePath");

                    b.HasKey("PictureId");

                    b.ToTable("Picture");
                });
#pragma warning restore 612, 618
        }
    }
}
