apiVersion: v1
kind: Service
metadata:
  name: people-service
  labels:
    app: people-service
spec:
  selector:
    app: people-service
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer