apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: people-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: people-service
    spec:
      containers:
      - name: people-service
        image: ./people-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080